version: '3'
services:
    app:
      build:
        context: .
        args:
        - BRANCH=${BRANCH-master}
      image: ninech/netbox:${BRANCH-latest}
      depends_on:
      - postgres
      env_file: netbox.env
      command:
      - ./manage.py
      - test
    postgres:
      image: postgres:9.6-alpine
      env_file: postgres.env
volumes:
  netbox-static-files:
    driver: local
  netbox-nginx-config:
    driver: local
